### ISSUE TITLE
TypeError: Cannot read property 'Container' of undefined

### ISSUE THREAD

**Issue by carantes** [cpetzel/react-native-flipper-xstate#1]
I am getting this error on Flipper for the xstate plugin.

```
TypeError: Cannot read property 'Container' of undefined
    at FlipperPlugin(xstate) (/Users/c.arantes-ferreira/.flipper/thirdparty/flipper-plugin-xstate/dist/bundle.js:783:61)
    at oh (file:///Applications/Flipper.app/Contents/Resources/app/bundle.js:53:58115)
    at $r (file:///Applications/Flipper.app/Contents/Resources/app/bundle.js:53:104290)
    at Qj (file:///Applications/Flipper.app/Contents/Resources/app/bundle.js:53:96846)
    at Kj (file:///Applications/Flipper.app/Contents/Resources/app/bundle.js:53:96771)
    at yj (file:///Applications/Flipper.app/Contents/Resources/app/bundle.js:53:93806)
    at file:///Applications/Flipper.app/Contents/Resources/app/bundle.js:53:45426
    at e.unstable_runWithPriority (file:///Applications/Flipper.app/Contents/Resources/app/bundle.js:55:3870)
    at cg (file:///Applications/Flipper.app/Contents/Resources/app/bundle.js:53:45135)
    at fg (file:///Applications/Flipper.app/Contents/Resources/app/bundle.js:53:45371)
    at gg (file:///Applications/Flipper.app/Contents/Resources/app/bundle.js:53:45306)
    at Ga (file:///Applications/Flipper.app/Contents/Resources/app/bundle.js:53:114465)
    at gd (file:///Applications/Flipper.app/Contents/Resources/app/bundle.js:53:22843)
```

flipper-plugin-xstate/dist/bundle.js
```
function Component() {
    return global.React.createElement(_flipperPlugin.Layout.Container, {
      rounded: false,
      grow: true
    }, global.React.createElement("iframe", {
      width: "100%",
      height: "100%",
      src: "https://statecharts.io/inspect?server=localhost:8189"
    }));
  }
```

**Comment by cpetzel** [comment]
What version of Flipper are you running?

**Comment by carantes** [comment]
Just upgraded Flipper to version 0.120.0 and now it is working fine. Great work on this plugin 👍
