### ISSUE TITLE
plugin fails to start in flipper

### ISSUE THREAD

**Issue by tristola** [cpetzel/react-native-flipper-xstate#4]
Versions:
Flipper: Version 0.174.0 (50.0.0)

    "@xstate/react": "^2.0.1",
    "xstate": "4.32.1"
    "react-native-flipper-xstate": "^1.0.5",
    "react-native-flipper": "0.171.1",

Errors:
Uncaught TypeError: process.nextTick is not a function
    at Receiver.receiverOnConclude (/Users/tristola/.flipper/installed-plugins/flipper-plugin-xstate/1.0.4/dist/bundle.js:1471:13)
    at Receiver.emit (node:events:390:28)
    at Receiver.controlMessage (/Users/tristola/.flipper/installed-plugins/flipper-plugin-xstate/1.0.4/dist/bundle.js:2393:16)
    at Receiver.getData (/Users/tristola/.flipper/installed-plugins/flipper-plugin-xstate/1.0.4/dist/bundle.js:2314:44)
    at Receiver.startLoop (/Users/tristola/.flipper/installed-plugins/flipper-plugin-xstate/1.0.4/dist/bundle.js:2159:24)
    at Receiver._write (/Users/tristola/.flipper/installed-plugins/flipper-plugin-xstate/1.0.4/dist/bundle.js:2104:12)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Receiver.Writable.write (node:internal/streams/writable:334:10)
    at Socket.socketOnData (/Users/tristola/.flipper/installed-plugins/flipper-plugin-xstate/1.0.4/dist/bundle.js:1541:37)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:199:23)

TypeError: Cannot read properties of undefined (reading 'startsWith')
    at l (ffe100b7dadf7d66cb287d8c1cac5c9e636a5bca.02734d24c079fd118957.js:1:87574)
    at Gi (framework.4dd1003cc9c949c7fcd3.js:1:70325)
    at ko (framework.4dd1003cc9c949c7fcd3.js:1:116864)
    at xu (framework.4dd1003cc9c949c7fcd3.js:1:109378)
    at wu (framework.4dd1003cc9c949c7fcd3.js:1:109303)
    at du (framework.4dd1003cc9c949c7fcd3.js:1:106305)
    at framework.4dd1003cc9c949c7fcd3.js:1:57587
    at t.unstable_runWithPriority (framework.4dd1003cc9c949c7fcd3.js:1:3942)
    at $l (framework.4dd1003cc9c949c7fcd3.js:1:57296)
    at Xl (framework.4dd1003cc9c949c7fcd3.js:1:57532)

**Comment by cpetzel** [comment]
Thanks for the report! 

Judging by the stack trace, The error seems to originate from the legacy inspector code.

I can try and take a peak at this next week, but hopefully this can get patched up by the stately team.

**Comment by tristola** [comment]
Did not figure out why this happened, but with newer version of flipper started working again. 
(version 0.176.1)
